### ISSUE TITLE
AWS Cognito support

### ISSUE THREAD

**Issue by bnfinet** [vouch/vouch-proxy#105]
from the #vouch irc channel...

Vouch Proxy is confirmed working with AWS Cognito

`oauth.user_info_url` must be set with upper case `I` for `oauth2/userInfo`

```
oauth:
  provider: oidc
  auth_url: https://YOURDOMAIN.auth.eu-west-2.amazoncognito.com/oauth2/authorize
  token_url: https://YOURDOMAIN.auth.eu-west-2.amazoncognito.com/oauth2/token
  user_info_url: https://YOURDOMAIN.auth.eu-west-2.amazoncognito.com/oauth2/userInfo
  scopes:
    - openid
    - email
    - profile
```
