### ISSUE TITLE
User whitelist by domain ?

### ISSUE THREAD

**Issue by moritan** [vouch/vouch-proxy#114]
Hello, 
Is it possible to define user whitelist by subdomain ? or do i need to do a docker instance ( and a config by subdomain ?

if i set domain to example.com.
I would be great to define  a spécific whitelist for app1.example.com and another one for app2.example.com

maybe something like that  (but better ;-) )
```
domains:
  - example.com

  # set allowAllUsers: true to use Vouch Proxy to just accept anyone who can authenticate at the configured provider
  # allowAllUsers: false

  # Setting publicAccess: true will accept all requests, even without a cookie. 
  # If the user is logged in, the cookie will be validated and the user header will be set.
  # You will need to direct people to the Vouch Proxy login page from your application.
  # publicAccess: false

  # whiteList 
  whiteList:
    - BySubdomain:
           name: app1
           users: 
                - bob@example.com
                - alice@example.com
     - BySubdomain:
           name: app2
           users: 
                - bob@example.com
                - joe@yourdomain.com

```

What could be great, is to define whitelist in a separate file whitelist.lst by example and be able to have filename like whitelist.<subdomain>.lst
