### ISSUE TITLE
Wrong auth-url

### ISSUE THREAD

**Issue by ksaffarian** [vouch/vouch-proxy#121]
Hey guys

I spent lots of time troubleshooting this issue!

The NGINX Ingress config that you suggested, is lacking one important part:
Instead of "nginx.ingress.kubernetes.io/auth-url: https://vouch.yourdomain.com" it should be "nginx.ingress.kubernetes.io/auth-url: https://vouch.yourdomain.com/**validate**"

If you do not set it like that, it goes to 30X redirect loop and does not open the main url.

Hope it helps others.

PS. Thanks for the good works.

**Comment by halkeye** [comment]
Your right, I just double checked my setup and I've been doing it without the validate

**Comment by halkeye** [comment]
Actually no, I don't think it should be, I read your thing backwards.

Its as per the docs, without the /validate

```
kubectl exec -n kube-system nginx-ingress-controller-5f757dfc97-9qrnl cat /etc/nginx/nginx.conf | grep auth_request
                        # ngx_auth_request module overrides variables in the parent request,
                        auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
                        auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
                        auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
                        auth_request        /_external-auth-Lw;
                        auth_request_set    $auth_cookie $upstream_http_set_cookie;
                        auth_request_set $authHeader0 $upstream_http_x_vouch_user;
```

Unless you are using a different nginx setup, that looks right to me

**Comment by bnfinet** [comment]
@ksaffarian are you seeing something different?

**Comment by bnfinet** [comment]
@halkeye in looking a little bit closer at this are you sure @ksaffarian isn't correct?

as per
https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/#key-detail

I'd suspect we should be using 
```
metadata:
  name: application
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://vouch.yourdomain.com/validate"
    nginx.ingress.kubernetes.io/auth-signin: "https://vouch.yourdomain.com/login?url=$escaped_request_uri"
```
Which would imply that the README is wrong and should have `/validate` there.  If we don't include `/validate` in the URL, where does it get the `/validate` endpoint from?
