### ISSUE TITLE
AAD configuration question

### ISSUE THREAD

**Issue by bjornicus** [vouch/vouch-proxy#135]
It seems like trying to use vouch with azure active directory doesn't quite work because, as far as I've been able to work out, it's failing trying to get the userinfo but doesn't realize it and tries to parse the response anyway.  Here is my vouch config:

```
# vouch config
# bare minimum to get vouch running with OpenID Connect (such as okta)

vouch:
  logLevel: debug
  # logLevel: info

  # testing - force all 302 redirects to be rendered as a webpage with a link
  # if you're having problems, turn on testing
  # testing: true

  # domains:
  # valid domains that the jwt cookies can be set into
  # the callback_urls will be to these domains
  domains:
  - {{env_base_url}}


oauth:
  # Generic OpenID Connect
  provider: oidc
  client_id: {{aad_app_client_id}}
  client_secret: {{aad_app_client_secret}}
  auth_url: https://login.microsoftonline.com/{{tenant}}/oauth2/v2.0/authorize
  token_url: https://login.microsoftonline.com/{{tenant}}/oauth2/v2.0/token
  user_info_url: https://login.microsoftonline.com/{{tenant}}/openid/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: https://{{vouch_host}}/auth
```

and the relevant log snippet 
```
{"level":"info","ts":1564012470.0837474,"msg":"OpenID userinfo body: %!(EXTRA string=)"}
{"level":"error","ts":1564012470.0837796,"msg":"Error unmarshaling claims"}
{"level":"error","ts":1564012470.0837836,"msg":"unexpected end of JSON input"}
{"level":"error","ts":1564012470.0837865,"msg":"unexpected end of JSON input"}
{"level":"debug","ts":1564012470.083794,"msg":"CaptureWriter.Write set w.StatusCode Ɛ"}
{"level":"debug","ts":1564012470.0838027,"msg":"Request handled successfully: 400"}
{"level":"info","ts":1564012470.0838099,"msg":"|400| 375.125433ms f
```

the suspicious line (to me) is `{"level":"info","ts":1564012470.0837474,"msg":"OpenID userinfo body: %!(EXTRA string=)"}` and digging a little further using manual curls of Microsoft's openid apis, I can get a code, and a token, but then when trying to call the userinfo endpoint it doesn't accept the jwt for that endpoint (seems like https://stackoverflow.com/questions/28631635/cannot-access-openid-userinfo-endpoint-on-azure-aadsts90010-jwt-tokens-cannot)

**Comment by artagel** [comment]
Try using adfs instead of oidc as a provider.  Adfs has the same behavior where you can only use the token once.  Getting the user info is handled slightly different than a regular oidc provider.

**Comment by bjornicus** [comment]
well, changing my provider to adfs makes it not work in a different way.  I'm now seeing an "Invalid session state" page (was also sometimes seeing a message about "Email  is not within a Vouch managed domain" on the page, and it's always in the log (below).  Not sure if the problem is actually domain related, or the fact that all of the profile fields seem to be empty (or something else).

```
{"level":"error","ts":1564024281.7485886,"msg":"jws: invalid token received"}
{"level":"debug","ts":1564024281.7489226,"msg":"/auth Claims from userinfo: {Claims:map[]}"}
{"level":"debug","ts":1564024281.749214,"msg":"/auth CallbackHandler"}
{"level":"debug","ts":1564024281.7494743,"msg":"/auth {Username: Name: Email: CreatedOn:0 LastUpdate:0 ID:0}"}
{"level":"warn","ts":1564024281.7496898,"msg":"domain  not found in any domains [bjorn.eng.hoy.lu]"}
{"level":"error","ts":1564024281.7500484,"msg":"Email  is not within a Vouch managed domain"}
{"level":"debug","ts":1564024281.7502897,"msg":"CaptureWriter.Write set w.StatusCode È"}
{"level":"debug","ts":1564024281.750571,"msg":"Request handled successfully: 200"}
{"level":"info","ts":1564024281.7508316,"msg":"|200| 40.345053ms /auth","statusCode":200,"request":19,"latency":0.040345053,"avgLatency":0.011281305,"ipPort":"172.1
```

**Comment by bjornicus** [comment]
I also get similar (but at least the name field is populated) if I use oidc but the v1 (e.g /oauth2/authorize) endpoints.  Fortunately I've now got it building and running in a local docker container so I can see if I can get it working with some code changes.

**Comment by bjornicus** [comment]
ah ha!  I some more googling finally revealed that the v2.0 userinfo endpoint is actually https://graph.microsoft.com/oidc/userinfo . (that stack overflow answer is 4 years old so I realized might be out of date).

I then I still had the vouch managed domain issue, but I apparently had a misunderstanding about the domains list in the vouch config.  The comment in the config says:
  # valid domains that the jwt cookies can be set into
  # the callback_urls will be to these domains

but it's not just the callback_url that needs to be in this list, but also the domain of the email address I use to sign in.  A little clarification there in the comments/docs would be useful

**Comment by artagel** [comment]
So, now it is working?
You should be able to see all your valid endpoints here: https://login.microsoftonline.com/{tenant}/.well-known/openid-configuration

**Comment by bnfinet** [comment]
@bjornicus if you would like to submit a PR (preferred) or suggest a specific change to the documentation wrt AAD I'd be happy to review it.

**Comment by bjornicus** [comment]
Thanks for the tip, I didn't know about teh .well-known list. Unfortunately it gives the original userinfo endpoint that does not accept a JWT, instead of the graph api one that does :(

Anyway, I think as far as documentation updates, it would be sufficient to add an AAD sample oauth config to the sample configs like this:

```
oauth:
  # Azure Active Directory
  provider: oidc
  client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  auth_url: https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize
  token_url: https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token
  user_info_url: https://graph.microsoft.com/oidc/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: http://vouch.yourdomain.com:9090/auth
```

and a update the comment about domains to something like 
```
  # valid domains that the jwt cookies can be set into or that vouch will accept logins from email addresses in those domains.
  # the callback_urls will be to these domains
```
