### ISSUE TITLE
Azure AD userinfo ID claim

### ISSUE THREAD

**Issue by hwshadow** [vouch/vouch-proxy#185]
started getting this message today.

> json: cannot unmarshal string into Go struct field User.id of type int

tracked it down to the fact that Azure userinfo endpoint started returning an `id` field that looks like `\"id\":\"alphanumeric-alphanumeric-alphanumeric-alphanumeric-alphanumeric\"` rather than what vouch is expecting (int)

 https://github.com/vouch/vouch-proxy/blob/ded2e2580345a0edd27aed5f2043e692e947845c/pkg/structs/structs.go#L23

Wonder how it was decided `id` should be an int?
Don't see it specified under https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims or https://connect2id.com/products/server/docs/api/userinfo#claims 

This flow was working fine yesterday, and just broke this morning.  Vouch configuration looks like

```
vouch:
  domains:
  - my.webpage.com

  jwt:
    issuer: Vouch
    maxAge: 120
    compress: true

  cookie:
    name: VouchCookie
    secure: true
    httpOnly: true
    maxAge: 480

  session:
    name: VouchSession
    
  headers:
    jwt: X-Vouch-Token
    querystring: access_token
    redirect: X-Vouch-Requested-URI

oauth:
  # Generic OpenID Connect
  provider: oidc
  client_id: "client_id_string"
  client_secret: "client_secret"
  auth_url: https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/authorize
  token_url: https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token
  user_info_url: https://graph.microsoft.com/oidc/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_urls:
    - https://my.webpage.com
```
