### ISSUE TITLE
ADFS Sample Configuration OR Any doc

### ISSUE THREAD

**Issue by llmuculusll** [vouch/vouch-proxy#191]
Hi,
Can you provide ADFS Sample Configuration or any documentation that guide how to configure Vouch-Proxy for ADFS?

**Comment by bnfinet** [comment]
@simongottschlag would you be able to add an example to the configs directory...

https://github.com/vouch/vouch-proxy/tree/master/config

**Comment by llmuculusll** [comment]
@simongottschlag  any new news about example or document?

**Comment by simongottschlag** [comment]
@bnfinet @llmuculusll 

The vouch-proxy configuration looks like this for us:
```YAML
vouch:
  logLevel: warning
  listen: 0.0.0.0
  port: 80
  AllowAllUsers: true
  cookie: 
    name: VouchCookie
    domain: example.com
    secure: true
    httpOnly: true
  headers:
    jwt: X-Vouch-Token
    querystring: access_token
    redirect: X-Vouch-Requested-URI
    idToken: X-Vouch-IdP-IdToken
  session:
    name: VouchSession
  jwt:
    secret: secretSauce
    maxAge: 59
oauth:
  provider: adfs
  client_id: k8s
  client_secret: sauceSecret
  auth_url: https://adfs.example.com/adfs/oauth2/authorize/
  token_url: https://adfs.example.com/adfs/oauth2/token/
  scopes:
    - openid
    - email
    - profile
  callback_url: https://vouch.example.com/auth
```

We are using the release `0.6.10` right now. We are using the same ADFS client for vouch-proxy and Kubernetes.

Our nginx configuration looks like this:
```
user  nginx;
worker_processes  3;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;
    proxy_http_version 1.1;

    proxy_cache_path /cache/validate levels=1:2 keys_zone=auth_cache:10m max_size=128m inactive=30m use_temp_path=off;

    server {
        listen       80;
        server_name  k8s-dashboard.example.com;

        # send all requests to the `/validate` endpoint for authorization
        auth_request /validate;

        location = /validate {
            internal;

            proxy_cache_valid 200 30s;
            proxy_cache auth_cache;
            proxy_cache_methods GET;
            proxy_cache_key $cookie_vouchcookie;

            proxy_buffer_size 128k;
            proxy_buffers 4 256k;
            proxy_busy_buffers_size 256k;
            
            proxy_set_header Host k8s-dashboard.example.com;
            proxy_pass http://vouch;

            # Vouch Proxy only acts on the request headers
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";

            # pass Vouch headers along with the request
            auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;
            auth_request_set $auth_resp_x_vouch_idp_idtoken $upstream_http_x_vouch_idp_idtoken;

            # these return values are used by the @error401 call
            auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
            auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
            auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
        }

        # if validate returns `401 not authorized` then forward the request to the error401block
        error_page 401 = @error401;

        location @error401 {
            # redirect to Vouch Proxy for login
            return 302 https://vouch.example.com/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
        }
        
        location / {
            proxy_pass https://kubernetes-dashboard.kube-system.svc.cluster.local;
            proxy_ssl_verify off;
            auth_request_set $auth_resp_x_vouch_idp_idtoken $upstream_http_x_vouch_idp_idtoken;
            proxy_set_header Authorization "Bearer $auth_resp_x_vouch_idp_idtoken";
        }
    }

    server {
        listen 80;
        server_name vouch.example.com;
        location / {
            proxy_set_header Host vouch.example.com;
            proxy_pass http://vouch;
        }
    }

    server {
        listen       8088;
        server_name  _;
        
        location /healthz {
            stub_status;
            access_log off;
            allow all;
        }
    }
}
```

We are running vouch-proxy, nginx and kubernetes-dashboard in Kubernetes - in the same namespace.
