### ISSUE TITLE
Configuration for Gitea

### ISSUE THREAD

**Issue by layanto** [vouch/vouch-proxy#203]
Vouch stated support for Gitea (https://github.com/vouch/vouch-proxy/pull/170) but I can't get it to work. Following Gitea oauth docs (https://docs.gitea.io/en-us/oauth2-provider/), I have configured vouch provider as follows:
```
oauth:

  provider: oidc
  client_id: xxxx
  client_secret: yyyy
  auth_url: https://gitea.example.com/login/oauth/authorize
  token_url: https://gitea.example.com/login/oauth/access_token
  user_info_url: ???
  callback_url: https://vouch.example.com/auth
```

I don't think Gitea oauth provides user information. If I left out user_info_url from vouch config.yml, I get panic error.

Appreciate help from anyone who managed to get integration with Gitea working. I will then raise PR with example to help the next person.

**Comment by layanto** [comment]
Looks like support for Gitea is not working until Gitea supports oauth user info (https://github.com/go-gitea/gitea/issues/8534). Maybe should update couch's readme to not claim support for Gitea and reference Gitea's GitHub issue.

**Comment by layanto** [comment]
Until Gitea supports user info, maybe consider adding Gitea as a separate provider without user info similar to IndieAuth, Google and ADFS?

**Comment by bnfinet** [comment]
Thanks for the recon.

Did you try with 'github' provider?

**Comment by aaronpk** [comment]
According to the Gitea docs, the URL to return the current user is `/user`

https://try.gitea.io/api/swagger#/user/userGetCurrent

If their response from that URL isn't compatible with the current set of things that Vouch understands, it would be relatively simple to create a PR for Vouch to read that format.

**Comment by aaronpk** [comment]
It looks like Gitea made their `/user` URL return `login` and `avatar_url` just like GitHub, so you should be able to use the GitHub provider and configure it with the Gitea routes

**Comment by layanto** [comment]
I will try with GitHub provider later today. But I saw this comment from one Gitea maintainer (I think) that suggested it won't work - https://github.com/go-gitea/gitea/pull/8962#issuecomment-553430770
But maybe that comment was referring to the implementation of the PR and not necessarily meant vouch with GitHub provider won't work.

**Comment by aaronpk** [comment]
Ignore that, they're talking about the internal implementation of their new userinfo endpoint.

I just tried it with the following config and it worked:

```yaml
oauth:
  provider: github
  client_id: XXXXX
  client_secret: XXXXX
  callback_url: http://vouch.example/auth
  auth_url: https://gitea.example/login/oauth/authorize
  token_url: https://gitea.example/login/oauth/access_token
  user_info_url: https://gitea.example/api/v1/user?token=
```
