### ISSUE TITLE
Accessing the user_info_url

### ISSUE THREAD

**Issue by psmod2** [vouch/vouch-proxy#230]
Hi,

Just started with vouch - in the config I see `user_info_url` is specified, however is it possible for me to request that URL directly?

https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example#L164

At the moment, I'm getting the cookie and hitting the user_info url with the PAccessToken myself - wondering if I can do that directly on Vouch's side?

Thanks.

**Comment by bnfinet** [comment]
What are you trying to do?  Why do you want to request `user_info_url` directly?

VP does access `user_info_url` to get the user info.  When you say "wondering if I can do that directly on Vouch's side?" what are hoping to get?

For anything specific to your setup please submit configs and logs.

**Comment by psmod2** [comment]
I was hoping to get the user's name e.g. first name.

**Comment by bnfinet** [comment]
Yes VP can.  If your IdP returns the name as a claim you can map the claim to an http header which can be populated and added to the request which is forwarded to your app...
https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example#L95-L103

**Comment by psmod2** [comment]
So are those claims the same as the scopes I have defined in my oauth

```
oauth:
  provider: oidc
  client_id: x
  client_secret: x
  auth_url: https://x.okta.com/oauth2/default/v1/authorize
  token_url: https://x/oauth2/default/v1/token
  user_info_url: https://x.okta.com/oauth2/default/v1/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: https://xx/callback
```

The name is basically found in the profile section - so would I therefore do:

```
headers:
    claims:
      - profile
```
