### ISSUE TITLE
Okta Logout - Not deleting the cookie

### ISSUE THREAD

**Issue by psmod2** [vouch/vouch-proxy#235]
Hello,

I'm implementing my logout button with Okta (with the help of comments posted here) I'm able to get the redirect, however its not removing the vouch cookie - although it one called removes VouchSession. 

Vouch Proxy sits between nginx - where I have the location:

```
location /tools/app/logout {
        proxy_pass http://vouch/logout;
}
```

Then the request thats made on my front end, hits this URL:

```
/tools/apps/logout?url=https://xxx.okta.com/oauth2/default/v1/logout?id_token_hint=${pIdToken}
```

Where `pIdToken` is obtained from the vouch cookie. 

Any ideas where I'm going wrong - its redirecting to the okta login page fine, or do I need to remove that cookie myself manually?

Thanks.

**Comment by bnfinet** [comment]
@psmod2 from here on out I'd ask you to please send your full nginx and VP configs (debug, testing) and fresh logs whenever you file an issue as well as any time where you have made any adjustments to your configs.

**Comment by psmod2** [comment]
Will do.

Heres my vouch config:

```
# vouch config

vouch:
  domains:
  - local-free.xxx.com
  - example-auth-proxy

  allowAllUsers: true

  jwt:
    compress: false

  cookie:
    name: CD_AccessToken
    httponly: false

oauth:
  provider: oidc
  client_id: ${OKTA_CLIENT_ID}
  client_secret: ${OKTA_CLIENT_SECRET}
  auth_url: https://xxxx.okta.com/oauth2/default/v1/authorize
  token_url: https://xxxx.okta.com/oauth2/default/v1/token
  user_info_url: https://xxxx.okta.com/oauth2/default/v1/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: https://local-free.xxxxx.com/tools/app/auth/callback
```

And here's the nginx config:

```
upstream vouch {
    # Location of the vouch proxy
    server ${AUTH_PROXY_HOST};
}

server {
    listen 443 ssl;
    server_name local-free.xxxx.com;

    ssl_certificate /etc/ssl/certs/b.xxxx.com.crt;
    ssl_certificate_key /etc/ssl/certs/b.xxxx.com.key;

    location /tools/app/auth/validate {
        # forward the /validate request to Vouch Proxy
        proxy_pass http://vouch/validate;
        # be sure to pass the original host header
        proxy_set_header Host $http_host;

        # Vouch Proxy only acts on the request headers
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";

        # Values used by the @error401 call
        auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
        auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
        auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }

    location /tools/app/logout {
        proxy_pass http://vouch/logout;
    }

    error_page 401 = @error401;

    # If the user is not logged in, redirect them to Vouch's login URL
    location @error401 {
        return 302 /tools/app/auth/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }

    location /tools/app/auth/callback {
        proxy_pass http://vouch/auth;
        # be sure to pass the original host header
        proxy_set_header Host $http_host;
    }

    location /tools/app/auth/ {
        proxy_pass http://vouch/;
        # be sure to pass the original host header
        proxy_set_header Host $http_host;
    }

    location /tools/app/ {
        auth_request /tools/app/auth/validate;

        proxy_pass http://${DASHBOARD_UI_HOST}/;
    }
}
```
