### ISSUE TITLE
Error: unexpected end of JSON input

### ISSUE THREAD

**Issue by tangel0v** [vouch/vouch-proxy#257]
Hi to all. We are not be able to extract the information of the token received from a ADFS 2019 platform. We are using _oidc_ as OAuth provider instead of adfs because it didn't work with our configuration. 

After receiving the token, the logs show the following information and we received an error in our browser with the phrase "unexpected end of JSON input":

{"level":"debug","ts":1588088738.494023,"msg":"ptokens: &{PAccessToken:FULLVALIDTOKEN}"}
{"level":"info","ts":1588088738.548036,"msg":"OpenID userinfo body: "}
{"level":"error","ts":1588088738.5480857,"msg":"Error unmarshaling claims"}
{"level":"error","ts":1588088738.5480921,"msg":"unexpected end of JSON input"}

The body seems to be empty but the token received is valid and if you decrypt it, you will see all the claims. Here is an example of the decrypted token received by Vouch from the ADFS server: https://hasteb.in/yorazule.json (the information is changed and it's not real).

We are using Firefox 75.0 and Chrome 81 in Windows and Linux. Vouch is installed in Kubernetes via Helm.

We also have reviewed this issue [first](https://github.com/vouch/vouch-proxy/issues/135) without success.

```yaml
oauth:
  provider: oidc
  client_id: 438333b9-267b-435e-bf18-7b366421bb7h
  client_secret: CENSORED
  auth_url: https://fed.miserere.com/adfs/oauth2/authorize
  token_url: https://fed.miserere.com/adfs/oauth2/token
  user_info_url: https://fed.miserere.com/adfs/userinfo
  scopes:
    - http://vouch.miserere.com/openid
    - email
    - profile
  callback_url: https://vouch.gcp.miserere.com/auth
```

This is our full configuration: https://hasteb.in/eyonigab.yaml . We are using the rule of $RELAYING_PARY/openid of ADFS to get extended tokens (we have tried the standard one without success).

If anyone is interested, these are the full logs: https://hasteb.in/esuzewof.json

Thank you very much for this incredible tool. It's amazing :D
