### ISSUE TITLE
versioned Alpine Docker images voucher/vouch-proxy:alpine-x.y.z

### ISSUE THREAD

**Issue by jeremyhermann** [vouch/vouch-proxy#269]
We were using a configuration like this that worked until a new version of the vouch-proxy alpine build was released today. Now we get an error message saying that we can't set both `allowAllUsers` and `domains`. 

We want users with any email address, who have authenticated with our Okta deployment, to be able to access the site, which seems to be what the `allowAllUsers` is for. However, when we remove the `domains` configuration, the `/validate` calls (made via localhost) fail. 

What is the correct way to use `allowAllIUsers` and `domains`?

Also, is there a way to pin to one of the older versions of the alpine docker build?

Here is our configuration that worked great up until today:

```
vouch:
  logLevel: debug

  port: 9090

  domains:
    - mydomain.ai
    - localhost

  allowAllUsers: true

oauth:
  provider: oidc
  client_id: ${OKTA_CLIENT_ID}
  client_secret: ${OKTA_CLIENT_SECRET}

  auth_url: https://login.mydomain.ai/oauth2/default/v1/authorize
  token_url: https://login.mydomain.ai/oauth2/default/v1/token
  user_info_url: https://login.mydomain.ai/oauth2/default/v1/userinfo
  scopes:
    - openid
    - email
  # Set the callback URL to the domain that Vouch is running on
  callback_url: https://vouch.mydomain.ai/auth
```
