### ISSUE TITLE
/auth Invalid session state: stored %!s(<nil>), returned 

### ISSUE THREAD

**Issue by Gourds** [vouch/vouch-proxy#342]
### Problem:
In the process of testing vouch-proxy, I encountered the following problem

###  vouch  proxy config
```
vouch:
  logLevel: debug
  testing: true
  listen: 0.0.0.0  # VOUCH_LISTEN
  port: 9090       # VOUCH_PORT
  cookie:
    domain: taiheops.com
#    secure: false
    sameSite: none
  allowAllUsers: true
oauth:
  provider: oidc
  client_id: xxxxxxxxxxxxxxxxxxx
  client_secret: xxxxxxxxxxxxxxxxxxx
  preferredDomain: taiheops.com
  auth_url: https://ynfyvjwiaw.login.aliyunidaas.com/oauth/authorize
  token_url: https://ynfyvjwiaw.login.aliyunidaas.com/oauth/token
  user_info_url: https://ynfyvjwiaw.login.aliyunidaas.com/api/bff/v1.2/oauth2/userinfo
  #user_info_url: https://ynfyvjwiaw.login.aliyunidaas.com/api/bff/v1.2/commons/user_details
  scopes:
    - read
    #- email
  callback_urls:
    #- http://test_sso_nginx_a.taiheops.com:2081/auth
    - http://vouch.taiheops.com:2081/auth
    #- http://127.0.0.1:9090/auth
```
### Nginx protect site config
```
server {
  listen 2081;
  server_name test_sso_nginx_a.taiheops.com;
  root /usr/share/nginx/html;
  index index.html;
#add
  auth_request /vouch-validate;
  location = /vouch-validate {
    # This address is where Vouch will be listening on
    proxy_pass http://127.0.0.1:9090/validate;
    proxy_pass_request_body off; # no need to send the POST body

    proxy_set_header Content-Length "";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # these return values are passed to the @error401 call
    auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
    auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
    auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
  }

  error_page 401 = @error401;
  # If the user is not logged in, redirect them to Vouch's login URL
  location @error401 {
    return 302 http://vouch.taiheops.com:9090/login?url=http://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
  }
}
```
### Nginx vouch config
```
server {
  listen 2081;
  server_name vouch.taiheops.com;
  #ssl_certificate /etc/letsencrypt/live/login.avocado.lol/fullchain.pem;
  #ssl_certificate_key /etc/letsencrypt/live/login.avocado.lol/privkey.pem;
  # Proxy to your Vouch instance
  location / {
    proxy_set_header  Host  vouch.taiheops.com;
    #proxy_set_header  X-Forwarded-Proto https;
    proxy_pass        http://127.0.0.1:9090;
  }
}
```

### Nginx vouch error log

```
2020-12-15T07:41:22.636Z	INFO	|200|   31.748µs /healthcheck	{"statusCode": 200, "request": 19, "latency": "31.748µs", "avgLatency": "63.037µs", "ipPort": "127.0.0.1:36862", "method": "GET", "host": "0.0.0.0:9090", "path": "/healthcheck", "referer": ""}
2020-12-15T07:41:52.543Z	DEBUG	/auth
2020-12-15T07:41:52.543Z	ERROR	/auth Invalid session state: stored %!s(<nil>), returned 6ff3f02eb78ff7dc833e7e3dd823ef716pp7QT9rd3d_idp
2020-12-15T07:41:52.543Z	DEBUG	setting the cookie domain to taiheops.com
2020-12-15T07:41:52.543Z	DEBUG	CaptureWriter.Write set w.StatusCode 400
2020-12-15T07:41:52.543Z	DEBUG	rendering error for user: 400 Bad Request
2020-12-15T07:41:52.543Z	INFO	|400|   143.93µs /auth	{"statusCode": 400, "request": 20, "latency": "143.93µs", "avgLatency": "67.081µs", "ipPort": "172.17.0.1:53069", "method": "GET", "host": "vouch.taiheops.com", "path": "/auth", "referer": ""}
```
