### ISSUE TITLE
Add support for the ClaimsParameter in the OIDC provider to support Twitch OIDC as IdP

### ISSUE THREAD

**Issue by vallahaye** [vouch/vouch-proxy#414]
Hello,

I recently started using Vouch Proxy for a small side project that involves authenticating through Twitch with OIDC.
Unfortunately, Twitch doesn't support [requesting claims using scope values](https://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims):

- The `email` and `profile` scopes are not supported
- At the moment, [the `user:read:email` scope does not set the `email` and `email_verified` claims in the UserInfo response](https://dev.twitch.tv/docs/authentication/getting-tokens-oidc#claims)

Instead, Twitch uses [the "claims" request parameter](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter) to do so. Example:

```
https://id.twitch.tv/oauth2/authorize?[...]scope=openid+user:read:email&claims={"userinfo":{"email":null,"email_verified":null,"preferred_username":null,"picture":null}}
```

I think adding the ability to set the claims parameter from the configuration when using the OIDC provider would greatly improve its generic nature. The previous example would then be expressed as follows in the configuration file:

```yaml
oauth:
  provider: oidc
  ...
  scopes:
    - openid
    - user:read:email
  claims:
    userinfo:
      email: null
      email_verified: null
      preferred_username: null
      picture: null
```

Apart from that, I would like to thank the Vouch development team for the quality of the solution provided. It is truly great.

Sincerely
