### ISSUE TITLE
Feature Request:  Allow custom qualifier and delimiter characters for claims value collections

### ISSUE THREAD

**Issue by masoncashews** [vouch/vouch-proxy#427]
## Describe the problem

When VP is returning a collection of claims values in a claim header, allow for the configuration of the text qualifier and separator.  Default is double quote qualified with comma separated.

**_Example_**
X-Vouch-IdP-Claims-group: [group1 group2]  by default is output as `"group1","group2"` in a header.

## Expected behavior
Have the separator and qualifier be configurable

```
vouch:  
... 
  headers:
    claims:
     - group
    claimsheaderformat:
      qualifier: ""
      delimiter: ";" 
```

This would output the header values (from the above example) as `group1;group2`

### Additional context
I ran across an issue with a third party application where they didn't support quoted values.  Which is a standard I know, but I figured others may have had a similar issue.  I tested these changes against my use case, so I figured it could be good for others.
