### ISSUE TITLE
Intermittent HTTP 400 errors

### ISSUE THREAD

**Issue by ajknv** [vouch/vouch-proxy#454]
I am running vouch-proxy to provide authentication to a service in an active-active highly available configuration. The service runs behind an AWS application load balancer which is providing the SSL termination. This basically works for the most part, but users are intermittently getting HTTP 400 error responses from vouch-proxy -- typically this seems to happen when they are already logged in but (probably) have been idle for a while. The logged error when it happens is this:

```
Feb 01 14:50:29 <HOST> vouch-proxy[980258]: {"level":"warn","ts":1643727029.765855,"msg":"/auth securecookie: the value is not valid: could not find session store VouchSession"}
Feb 01 14:50:29 <HOST> vouch-proxy[980258]: {"level":"info","ts":1643727029.7660384,"msg":"|400|  190.332µs /sf/auth/fMz2gq9up6Nb13qkeIB5BSqH5w8qVMYN/","statusCode":400,"request":34482,"latency":0.000190332,"avgLatency":0.000801226,"ipPort":"127.0.0.1:49284","method":"GET","host":"<LB_DNS_NAME>","path":"/sf/auth/fMz2gq9up6Nb13qkeIB5BSqH5w8qVMYN/","referer":""}
```

From my efforts at searching it seems that one possibility is that this is related to the secure setting on the cookies, given that all the configuration apparent to Vouch is plain HTTP. But I do not want to disable the secure cookie setting as suggested in some issue reports, since of course the actual client connections are HTTPS and it is just the upstream SSL termination that "hides" this from the vouch-proxy/nginx configuration. It seems like for this setup vouch-proxy might need something akin to the "trust proxy" setting found in node.js (https://stackoverflow.com/questions/23413401/what-does-trust-proxy-actually-do-in-express-js-and-do-i-need-to-use-it), but I cannot find any comparable config setting.

Attached are my vouch and nginx configuration files; I'm hoping maybe there's something else I might be missing.

```
vouch:
  # domains:
  # valid domains that the jwt cookies can be set into
  # the callback_urls will be to these domains
  domains:
  - <DOMAIN1>
  - <DOMAIN2>
  - 192.168.22.11
  - 192.168.22.26

  jwt:
    # A random string used to cryptographically sign the JWT when signing_method is set to HS256, HS384 or HS512.
    # Vouch Proxy complains if the string is less than 44 characters (256 bits as 32 base64 bytes).
    # Needs to be the same across all instances in an HA setup.
    secret: <SECRETA>

  cookie:
    name: VouchCookie     # has to be the same name as in nginx for caching: proxy_cache_key $cookie_vouchcookie;
    secure: true
    domain: <DOMAIN1>
    httpOnly: true
    sameSite: lax

  session:
    secret: <SECRETB>

  headers:
    idtoken: X-Vouch-IdP-IdToken

    claims:
      - name
      - email
      - roles

  post_logout_redirect_uris:
    - https://<APP>/login

  # document_root - VOUCH_DOCUMENT_ROOT
  # see README for `Vouch Proxy "in a path"` - https://github.com/vouch/vouch-proxy#vouch-proxy-in-a-path
  document_root: /sf

oauth:
  # Generic OpenID Connect
  provider: oidc
  client_id: <OAUTH_ID>
  client_secret: <OAUTH_SECRET>
  auth_url: https://<OAUTH_ENDPOINT>/authorize
  token_url: https://<OAUTH_ENDPOINT>/token
  user_info_url: https://<OAUTH_ENDPOINT>/userinfo
  scopes:
    - openid
    - email
    - profile
    - authz
  callback_url: https://<APP>/sf/auth
```

```
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    server {
        server_name          <APP_HOST>;
        listen               8080;
        keepalive_timeout    70;
        gzip                 on;
        server_tokens        off;
        client_max_body_size 25m;

        # This location serves all Vouch Proxy endpoints as /sf/$uri
        location /sf {
          proxy_pass http://127.0.0.1:9090; # must not! have a slash at the end
          proxy_set_header Host $http_host;
          proxy_pass_request_body off;
          proxy_set_header Content-Length "";
          proxy_set_header X-Forwarded-Proto https;

          # these return values are used by the @error401 call
          auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
          auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
          auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
        }

        # if /vp_in_a_path/validate returns `401 not authorized` then forward the request to the error401block
        error_page 401 = @error401;

        location @error401 {
            # redirect to Vouch Proxy for login
            return 302 https://<APP_HOST>/sf/login?url=https://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
        }

        location /api {
            # Bypass auth_request for API calls
            proxy_pass http://127.0.0.1:8001;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /static/ {
            alias /opt/<APP_PATH>/static/;
        }

        location / {
            auth_request /sf/validate;
            auth_request_set $auth_user $upstream_http_x_vouch_user;
            auth_request_set $auth_roles $upstream_http_x_vouch_idp_claims_roles;

            auth_request_set $auth_cookie $upstream_http_set_cookie;
            add_header Set-Cookie $auth_cookie;
            auth_request_set $auth_status $upstream_status;

            proxy_pass http://127.0.0.1:8001;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;

            proxy_set_header REMOTE_USER $auth_user;
            proxy_set_header REMOTE_USER_ROLES $auth_roles;
        }
    }
}
```
