### ISSUE TITLE
configuration file not found: While parsing config: yaml: line 19: did not find expected key

### ISSUE THREAD

**Issue by wasweisic** [vouch/vouch-proxy#456]
Hey, I am using vouch-proxy via docker with following command:
```
sudo docker run -d -p 9090:9090 --name vouch-proxy -v /etc/vouch/config:/config quay.io/vouch/vouch-proxy
```
The /etc/vouch/config directory contains the config.yml file with following content:
```
vouch:
   allowAllUsers: true
   cookie:
     domain: example.com
oauth:
  provider:oidc:
 -client-information-
```

Here's the log files i get once running **"docker start vouch-proxy"**:
```
{"level":"fatal","ts":1644338344.925953,"msg":"configuration file not found: While parsing config: yaml: line 19: did not find expected key"}
{"level":"debug","ts":1644338773.711656,"msg":"Vouch Proxy was executed as '/vouch-proxy' (pid: 1) running as user vouch (uid: 999) with group vouch (gid: 999)"}
```
What I tried so far:
-using chown 777 on the config.yml
-created a vouch user with 999:999 and using chown on the file
-using docker run --user $UID:$GID with my default user
