### ISSUE TITLE
Allow wildcard usage in whiteList param

### ISSUE THREAD

**Issue by nrukavkov** [vouch/vouch-proxy#471]
Hello. How can I allow to be authenticated for all users from one domain and some users for another?

I think it whould be nice to use construction in config file like:

whiteList:
 - *@onedomain.com
 - user1@seconddomain.com
 - user2@seconddomain.com
 
 Or allow to use regexp?

**Comment by Aspersat** [comment]
if i figured it out correctly the following config should have exactly this effect.. but... im very new to vouch and i could missinterpret what i experienced:;
 ``` 
vouch:
 domains:
  - aspergillus.ch
  
  whiteList:
  - r.glaettli@gmail.com
  ```
