### ISSUE TITLE
Add _FILE environment variable variants to read sensitive configuration from files

### ISSUE THREAD

**Issue by Radiergummi** [vouch/vouch-proxy#475]
We're running Vouch in our Swarm cluster. All applications are configured from the CI deployment pipeline, and Vouch is no exception here. Currently, the JWT secret and OAuth provider configuration have to be passed as environment variables, which provides no protection for the values, so they are visible from internal monitoring dashboards which are accessible to all developers. We would like to restrict access to sensitive data like the OAuth client credentials however.

This is easily possible by using [Docker Secrets](https://docs.docker.com/engine/swarm/secrets/), which essentially mount secret values as files below `/run/secret/`. Lots of applications include support for `ACME_SECRET` and `ACME_SECRET_FILE` to allow passing the path of a file instead of the secret value itself.

It would be great if Vouch supported `_FILE` variants of sensitive configuration settings, or maybe just all of them!

In the mean time, there's a workaround: Dynamically generating a configuration file and providing that as a secret:
```yaml
services:
  vouch:
    environment:
      VOUCH_CONFIG: /config/dynamic_config.yaml
      # place other configuration here
    secrets:
      - source: vouch_config
        target: /config

secrets:
  vouch_config:
    file: ./dynamic_config.yaml
```
The configuration itself could be written using something like this in a build script:
```bash
echo jwt.secret=$JWT_SECRET >> ./dynamic_config.yaml
echo oauth.client_id
```
