### ISSUE TITLE
How to pass OAuth2 ADFS token to server application?

### ISSUE THREAD

**Issue by konachan700** [vouch/vouch-proxy#526]
How to pass OAuth2 ADFS token to server application?
I did in config.yml:
```
headers:
  idtoken: mytoken
  claimheader: ""
  claims:
    - idtoken
```
I did in nginx locations /validate and /:
`auth_request_set $auth_resp_mytoken $upstream_http_mytoken;`

And $auth_resp_mytoken is empty. All other variables, for example $upstream_http_x_vouch_user, contain correct values. If I use default headers names, I obtain an empty idtoken too. I see this token in vouch logs...

What am I doing wrong?
