### ISSUE TITLE
Infinite re-directs when I set `allowAllUsers: false`.

### ISSUE THREAD

**Issue by vulcan25** [vouch/vouch-proxy#60]
I have included a config below which works with github as my auth provider.  I have tested this; once I authenticate with github, I am redirected back to my protected endpoint and everything is great.

**The problem:** I wish to define allowed users in the whitelist, so only a few friends can get access to my protected endpoint.  For this reason I change `allowAllUsers: false`.  The whitelist is already defined.

Immediately upon restarting the service (`docker kill vouch-proxy ; docker rm vouch-proxy` followed by the `docker run` command below) I hit the private endpoint in my browser, and enter an infinite loop betwen login.example.com and github.com, until github asks me to re-authorize the request due to too many attempts.  At one point I got a short rate ban.

My issues seem similar to [this thread](https://github.com/vouch/vouch-proxy/issues/42) logged by @brettp  What I took from that thread was not to list all the subdomains (private.example.com, login.example.com) under `vouch.domains` which I have followed.

I'm not sure what's wrong with my config.  I'm hoping it's something obvious.  I'm not sure if I've used incorrect YML syntax/indentation anywhere.  I can add further information if required.  

I launch it with:
```
docker run -d \
    -p 9090:9090 \
    --name vouch-proxy \
    -v ${PWD}/config:/config \
    -v ${PWD}/data:/data \
    voucher/vouch-proxy
```

My config.yml:
```
vouch:
  # logLevel: debug
  logLevel: info
  listen: 0.0.0.0
  port: 9090

  # domains
  # each of these domains must serve the url https://vouch.$domains[0] https://vouch.$domains[1] ...
  # so that the cookie which stores the JWT can be set in the relevant domain
  # usually you'll just have one.
  # Comment this out if you set allowAllUser:true
  domains:
   - example.com
  # set allowAllUsers: true to use Vouch Proxy to just accept anyone who can authenticate at the configured provider
  allowAllUsers: true

  # Setting publicAccess: true will accept all requests, even without a cookie. 
  # If the user is logged in, the cookie will be validated and the user header will be set.
  # You will need to direct people to the Vouch Proxy login page from your application.
  publicAccess: false

  # whiteList (optional) allows only the listed usernames
  # usernames are usually email addresses (google, most oidc providers) or login/username for github and github enterprise
  whiteList:
  - vulcan25
  - anotheruser
    
  jwt:
    # secret: a random string used to cryptographically sign the jwt
    # Vouch Proxy complains if the string is less than 44 characters (256 bits as 32 base64 bytes)
    # if the secret is not set here then..
    # look for the secret in `./config/secret`
    # if `./config/secret` doesn't exist then randomly generate a secret and store it there
    # in order to run multiple instances of vouch on multiple servers (perhaps purely for validating the jwt),
    # you'll want them all to have the same secret
    secret: TOTALLY_SECRET_STRING
    issuer: Vouch
    # number of minutes until jwt expires
    maxAge: 240
    # compress the jwt
    compress: true

  cookie: 
    # name of cookie to store the jwt
    name: VouchCookie
    # optionally force the domain of the cookie to set
    domain: example.com
    secure: true
    httpOnly: true

  session:
    # just the name of session variable stored locally
    name: vouchSession

  headers:
    jwt: X-Vouch-Token
    querystring: access_token
    redirect: X-Vouch-Requested-URI

  db: 
    file: data/vouch_bolt.db

  # testing: force all 302 redirects to be rendered as a webpage with a link
  #testing: true
  # test_url: add this URL to the page which vouch displays
  #test_url: http://yourdomain.com
  # webapp: WIP for web interface to vouch (mostly logs)
  webapp: true

#
# OAuth Provider
# configure ONLY ONE of the following oauth providers
#
oauth:

  # GitHub
  # https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/
  provider: github
  client_id: myclientid
  client_secret: mysecretkey
  callback_urls:
   - https://login.example.com/auth
  scopes:
   - ''
```
