### ISSUE TITLE
Cookie Domain not being imported

### ISSUE THREAD

**Issue by simongottschlag** [vouch/vouch-proxy#65]
Hi,

Sorry if this is me not understanding Go. I've been looking at an issue where my cookie.domain isn't being set for the cookies.

I've forked and built the project and added the following:
log.Debugf("temp debug - cookie: %v", cfg.Cfg.Cookie)

Which is returned like this:
time="2019-02-05T10:17:18Z" level=debug msg="temp debug - cookie: {VouchCookie  false true}"

I can see, at startup, that it is configured. Seems like cookie.go isn't using the configuration set?

Am I just doing everything wrong here or is there a bug?

**Comment by simongottschlag** [comment]
This is the output:
```
time="2019-02-05T10:58:53Z" level=debug msg="map[vouch:map[allowallusers:true loglevel:debug port:80 listen:0.0.0.0] oauth:map[scopes:[openid email profile] user_info_url:https://adfs.example.com/adfs/userinfo callback_url:https://auth.example.com/auth provider:oidc client_id:clientId token_url:https://adfs.example.com/adfs/oauth2/token/ auth_url:https://adfs.example.com/adfs/oauth2/authorize/ client_secret:***] cookie:map[httponly:false secure:false name:VouchCookieTest domain:example.com] headers:map[jwt:X-Vouch-Token querystring:access_token redirect:X-Vouch-Requested-URI] session:map[name:VouchSession]]"
```

When reading it from main it looks like this: (used %s instead of %v)
```
time="2019-02-05T10:58:53Z" level=debug msg="debug - main cfg {debug 0.0.0.0 %!s(int=80) [] [] %!s(bool=true) %!s(bool=false) {%!s(int=240) Vouch *** %!s(bool=true)} {VouchCookie  %!s(bool=false) %!s(bool=true)} {X-Vouch-Token X-Vouch-User access_token X-Vouch-Requested-URI X-Vouch-Success} {data/vouch_bolt.db} {VouchSession ***}  [] %!s(bool=false) %!s(bool=false)}"
```

It really seems like I'm not getting the settings to other places other than cfg.go.

This is the config.yml:
```
vouch:
  logLevel: debug
  listen: 0.0.0.0
  port: 80
  AllowAllUsers: true
cookie: 
  name: VouchCookieTest
  domain: example.com
  secure: false
  httpOnly: false
headers:
  jwt: X-Vouch-Token
  querystring: access_token
  redirect: X-Vouch-Requested-URI
session:
  name: VouchSession
oauth:
  provider: oidc
  client_id: clientId
  client_secret: ***
  auth_url: https://adfs.example.com/adfs/oauth2/authorize/
  token_url: https://adfs.example.com/adfs/oauth2/token/
  user_info_url: https://adfs.example.com/adfs/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: https://auth.example.com/auth
```
