### ISSUE TITLE
Does it work it with ADFS 2012R2 (Active Directory Federation Services)?

### ISSUE THREAD

**Issue by rerime** [vouch/vouch-proxy#77]
Does it work it with ADFS  2012R2 or 2016 (Active Directory Federation Services)?
OAUTH 2.0?
Please provide documentation how to setup.

**Comment by bnfinet** [comment]
@simongottschlag has recently contributed #68 for ADFS support.

I'm uncertain about support for ADFS 2012R2 specifically but I think it should work with an `oauth.provider: oidc` config such as...

```
oauth:
  provider: oidc
  client_id: yourclientId
  client_secret: ***
  auth_url: https://adfs.example.com/adfs/oauth2/authorize/
  token_url: https://adfs.example.com/adfs/oauth2/token/
  user_info_url: https://adfs.example.com/adfs/userinfo
  scopes:
    - openid
    - email
    - profile
  callback_url: https://auth.example.com/auth
```

@simongottschlag does that look right to you? ^^

See PR #68 and issue #65 for further discussion.

@rerime please do let us know if that works.  I'll leave this open for now.

**Comment by simongottschlag** [comment]
Hi,

The following works:
```
vouch:
  logLevel: warning
  listen: 0.0.0.0
  port: 80
  AllowAllUsers: true
  cookie: 
    name: VouchCookie
    domain: example.com
    secure: true
    httpOnly: true
  headers:
    jwt: X-Vouch-Token
    querystring: access_token
    redirect: X-Vouch-Requested-URI
  session:
    name: VouchSession
  jwt:
    secret: secret
    maxAge: 59
oauth:
  provider: adfs
  client_id: clientId
  client_secret: secret
  auth_url: https://adfs.example.com/adfs/oauth2/authorize/
  token_url: https://adfs.example.com/adfs/oauth2/token/
  scopes:
    - openid
    - email
    - profile
  callback_url: https://vouch.example.com/auth
```

Only tested with ADFS 2016 (v4). You can try the following:
```
$name = 'vouch'
$environment = 'dev'
$vouchProxyAddr = "https://auth.example.com/auth"

$ClientRoleIdentifier = "$name-$environment".ToLower()
$ServerRoleIdentifier = @(
    "$name`://$environment",
    $vouchProxyAddr
)

New-AdfsApplicationGroup -Name "$ClientRoleIdentifier" -ApplicationGroupIdentifier "$ClientRoleIdentifier"
$ADFSApp = Add-AdfsServerApplication -Name "$ClientRoleIdentifier - Server application" -ApplicationGroupIdentifier "$ClientRoleIdentifier" -RedirectUri $ServerRoleIdentifier -Identifier "$ClientRoleIdentifier" -GenerateClientSecret

$params = @{
    Name="$ClientRoleIdentifier - Web API"
    ApplicationGroupIdentifier="$ClientRoleIdentifier"
    Identifier=$ServerRoleIdentifier
    IssueOAuthRefreshTokensTo="AllDevices"
    RefreshTokenProtectionEnabled=$false
    AccessControlPolicyName="Permit specific group"
    AccessControlPolicyParameters=@{
        GroupParameter=$LoginGroupName
    }
}

Add-AdfsWebApiApplication @params

Grant-AdfsApplicationPermission -ClientRoleIdentifier $ClientRoleIdentifier -ServerRoleIdentifier $ServerRoleIdentifier[0] -ScopeNames @('allatclaims','profile','openid')
Write-Output "`r`nPlease write down and save the following Client Secret: $($ADFSApp.ClientSecret)`r`n"
```
