### ISSUE TITLE
"no jwt found in request" and multiple redirects

### ISSUE THREAD

**Issue by msarti** [vouch/vouch-proxy#84]
I'm trying to configure a local server with Ubuntu and Nginx and OpenId (Okta) authentication.
I configured two virtualhosts:
- test.sarti.lan (site to be protected)
- vouch.sarti.lan (reverse proxy to vouch)
The two hostnames are local and mapped in /etc/hosts (both server and client).
While authentication appears to work, the site goes into an infinite redirect loop and the call to "validate" produces the "**no jwt found in request**" error.
This is the vouch configuration:
```
vouch:
  logLevel: debug
  listen: 0.0.0.0
  port: 9090
  domains:
  - sarti.lan
  whiteList:
  - email@address.com

  jwt:
    secret: your_random_string
    issuer: Vouch
    maxAge: 240
    compress: true

  cookie:
    name: VouchCookie
    secure: true
    httpOnly: true

  session:
    name: VouchSession
    key: you_random_key

  headers:
    jwt: X-Vouch-Token
    querystring: access_token
    redirect: X-Vouch-Requested-URI
  db:
    file: data/vouch_bolt.db
  testing: true
  test_url: http://yourdomain.com
  webapp: true

oauth:
  provider: oidc
  client_id: clientId
  client_secret: secret
  auth_url: https://dev-xxxx.okta.com/oauth2/default/v1/authorize
  token_url: https://dev-xxxx.okta.com/oauth2/default/v1/token
  user_info_url: https://dev-xxxx.okta.com/oauth2/default/v1/userinfo
  scopes:
    - openid
    - email
  callback_url: http://vouch.sarti.lan/auth

```
This is the nginx configuration for test site:
```
server {
  #listen 443 ssl http2;
  server_name test.sarti.lan;
  listen 80;
  #ssl_certificate /etc/nginx/ssl/nginx.crt;
  #ssl_certificate_key /etc/nginx/ssl/nginx.key;

        access_log /var/log/nginx/access_login.log;
        error_log /var/log/nginx/error_login.log;
  
  root /var/www/html;
  
  index index.html;

    # Any request to this server will first be sent to this URL
    auth_request /validate;
    location = /validate {
      internal;
      # Vouch Proxy can run behind the same nginx-revproxy
      # May need to add "internal", and comply to "upstream" server naming
      proxy_pass http://vouch.sarti.lan:9090;

      # Vouch Proxy only acts on the request headers
      proxy_pass_request_body off;
      proxy_set_header Content-Length "";

      # pass X-Vouch-User along with the request
      auth_request_set $auth_resp_x_vouch_user $upstream_http_x_vouch_user;

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;
    }

    # if validate returns `401 not authorized` then forward the request to the error401block
    error_page 401 = @error401;

    location @error401 {
        # redirect to Vouch Proxy for login
        return 302 http://vouch.sarti.lan/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;
    }
}

```
This is the vouch reverse proxy config:
```
server {
  listen 80 default_server;
  server_name vouch.sarti.lan;

  # listen 443 ssl;

  # ssl_certificate /etc/nginx/ssl/nginx.crt;
  # ssl_certificate_key /etc/nginx/ssl/nginx.key;

        access_log /var/log/nginx/access_login.log;
        error_log /var/log/nginx/error_login.log;


  # Proxy to your Lasso instance
  location / {
    proxy_set_header  Host  vouch.sarti.lan;
    # proxy_set_header  X-Forwarded-Proto https;
    proxy_pass        http://vouch.sarti.lan:9090;
  }
}
```
and finally this is the relevant parts of vouch log:

```
DEBU[0044] /auth                                        
INFO[0045] OpenID userinfo body:  {"sub":"00ud1304hu0lwKoXs356","email":"email@address.com","email_verified":true} 
DEBU[0045] CallbackHandler                              
DEBU[0045] {email@address.com  email@address.com 0 0 0} 
DEBU[0045] found user.Username in WhiteList: email@address.com 
DEBU[0045] key is email@address.com         
DEBU[0045] retrieved email@address.com from db 
DEBU[0045] userexists.. keeping time at 1552740939      
DEBU[0045] user created {email@address.com  email@address.com 1552740939 1552820656 0} 
DEBU[0045] token: &{ 0xc0001461a0 map[typ:JWT alg:HS256] {email@address.com [sarti.lan] { 1552835056  0 Vouch 0 }}  false} 
DEBU[0045] token expires: 1552835056                    
DEBU[0045] diff from now: 14400                         
DEBU[0045] compressed string: H4sIAAAAAAAA_xTNYW6CMBQA4BPN0LqR8dOw0LwKJTraMP_RovC0D43goJx-2Qm-c5C9FQ5LlKBXYAphhOH44VKI4faoTSqTzTlI5rgJlrLp9A0xEOsdqd98UL0bjo89T56tyHZOLL2lNtitmXPyEeCMjvvoVBdY-hEdz0Irbi8rshf4aAQy7_9QUWlWXLtVVTumcMamVitc72goYT-8w8thM0k4LFyZsqFm2tM2-rz4JhaxHnN9T-pn-qa-qspa6PRfAAAA__9rU1H10wAAAA== 
DEBU[0045] domain vouch.sarti.lan matched array value at [0]=sarti.lan 
DEBU[0045] CaptureWriter.Write set w.StatusCode 200     
DEBU[0045] Request handled successfully: 200            
INFO[0045] | 200 | 1.801522841s /auth        avgLatency=601.373179ms host=vouch.sarti.lan ipPort="192.168.122.67:48208" latency=1.801522841s method=GET path=/auth referer= request=3 statusCode=200
DEBU[0189] Request received : &{GET /validate HTTP/1.0 1 0 map[Connection:[close] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3] Referer:[http://vouch.sarti.lan/auth?code=M1D1sJ7BArlbpfpWNvCd&state=dkqzHMKOcgXWXfehX8jNYkQfbV_yY6OLSCaSv64iRDg%3D] Accept-Encoding:[gzip, deflate] Accept-Language:[it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7]] {} <nil> 0 [] true vouch.sarti.lan:9090 map[] map[] <nil> map[] 192.168.122.67:48212 /validate <nil> <nil> <nil> 0xc0004de210} 
DEBU[0189] /validate                                    
ERRO[0189] no jwt found in request                      
DEBU[0189] domain vouch.sarti.lan:9090 matched array value at [0]=sarti.lan 
DEBU[0189] CaptureWriter.WriteHeader set w.StatusCode 401 
DEBU[0189] Request handled successfully: 401            
INFO[0189] | 401 | 7.764646ms /validate      avgLatency=452.971046ms host="vouch.sarti.lan:9090" ipPort="192.168.122.67:48212" latency=7.764646ms method=GET path=/validate referer="http://vouch.sarti.lan/auth?code=M1D1sJ7BArlbpfpWNvCd&state=dkqzHMKOcgXWXfehX8jNYkQfbV_yY6OLSCaSv64iRDg%3D" request=4 statusCode=401
DEBU[0189] Request received : &{GET /login?url=http://test.sarti.lan/&vouch-failcount=&X-Vouch-Token=&error= HTTP/1.0 1 0 map[Accept-Language:[it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7] Cookie:[VouchSession=MTU1MjgyMDY1NnxEdi1CQkFFQ180SUFBUkFCRUFBQV81Yl9nZ0FEQm5OMGNtbHVad3dZQUJab2RIUndPaTh2ZEdWemRDNXpZWEowYVM1c1lXNHZBMmx1ZEFRQ0FBQUdjM1J5YVc1bkRBY0FCWE4wWVhSbEJuTjBjbWx1Wnd3dUFDeGthM0Y2U0UxTFQyTm5XRmRZWm1Wb1dEaHFUbGxyVVdaaVZsOTVXVFpQVEZORFlWTjJOalJwVWtSblBRWnpkSEpwYm1jTURnQU1jbVZ4ZFdWemRHVmtWVkpNQm5OMGNtbHVad3dDQUFBPXxny9yz0NaYQO8MsQNbM5p5oxy8vgGhTBYeB2EMc5S-8Q==] Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3] Referer:[http://vouch.sarti.lan/auth?code=M1D1sJ7BArlbpfpWNvCd&state=dkqzHMKOcgXWXfehX8jNYkQfbV_yY6OLSCaSv64iRDg%3D] Accept-Encoding:[gzip, deflate] Connection:[close]] {} <nil> 0 [] true vouch.sarti.lan map[] map[] <nil> map[] 192.168.122.67:48214 /login?url=http://test.sarti.lan/&vouch-failcount=&X-Vouch-Token=&error= <nil> <nil> <nil> 0xc0004de630} 
DEBU[0189] /login                                       
DEBU[0189] domain vouch.sarti.lan matched array value at [0]=sarti.lan 
DEBU[0189] session state set to K6XxOxJ-w6V3kR434t2euIIzrNMXuLgm_e_K6THq8DA= 
DEBU[0189] session requestedURL set to http://test.sarti.lan/ 
DEBU[0189] failcount for http://test.sarti.lan/ is 0    
DEBU[0189] saving session                               
DEBU[0189] redirecting to oauthURL https://dev-xxxx.okta.com/oauth2/default/v1/authorize?client_id=clientId&redirect_uri=http%3A%2F%2Fvouch.sarti.lan%2Fauth&response_type=code&scope=openid+email&state=K6XxOxJ-w6V3kR434t2euIIzrNMXuLgm_e_K6THq8DA%3D 
DEBU[0189] CaptureWriter.Write set w.StatusCode 200     
DEBU[0189] Request handled successfully: 200            
INFO[0189] | 200 | 16.710798ms /login        avgLatency=365.718997ms host=vouch.sarti.lan ipPort="192.168.122.67:48214" latency=16.710798ms method=GET path=/login referer="http://vouch.sarti.lan/auth?code=M1D1sJ7BArlbpfpWNvCd&state=dkqzHMKOcgXWXfehX8jNYkQfbV_yY6OLSCaSv64iRDg%3D" request=5 statusCode=200
```
